import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = resolve(__dirname, '../../..')
const workflow = readFileSync(resolve(root, '.github/workflows/windows-package.yml'), 'utf8').replace(/\r\n/g, '\n')
const publisher = readFileSync(resolve(root, 'scripts/publish-demo-release.sh'), 'utf8').replace(/\r\n/g, '\n')

describe('demo server publish contract', () => {
  it('publishes verified main builds to the existing demo release root', () => {
    expect(workflow).toContain("github.ref == 'refs/heads/main'")
    expect(workflow).toContain('needs: package')
    expect(workflow).toContain('actions/download-artifact@v8')
    expect(workflow).toContain('DEV_SSH_HOST')
    expect(workflow).toContain('DEV_SSH_USER')
    expect(workflow).toContain('DEV_SSH_PASSWORD')
    expect(workflow).toContain('SHA256:i5zZS4Ydc4iAFzY8xpI0Md/bi/sCzzwcGMf9P6n06Dc')
    expect(workflow).toContain('Demo SSH host fingerprint mismatch')
    expect(workflow).toContain('/var/www/family-circle-prod/electron-releases/demo')
    expect(workflow).toContain('scripts/publish-demo-release.sh')
    expect(workflow).toContain('https://familycircle.o2gventures.com')
    expect(workflow).toContain('public_base_path="/electron-releases/demo"')
    expect(workflow).toContain('public_path="$public_base_path/latest/$installer"')
    expect(workflow).toContain('report-demo-status:')
    expect(workflow).toContain("if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}")
    expect(workflow).toContain('needs:\n      - package\n      - deploy-demo')
    expect(workflow).toContain('statuses: write')
    expect(workflow).toContain('PACKAGE_RESULT: ${{ needs.package.result }}')
    expect(workflow).toContain('DEPLOY_RESULT: ${{ needs.deploy-demo.result }}')
    expect(workflow).toContain('context="demo-server-deploy"')
    expect(workflow).toContain('Windows package failed; demo not deployed')
    expect(workflow).toContain('Demo server deployment verified')
    expect(workflow).toContain('Demo server deployment was skipped')
    expect(workflow).toContain('Demo server deployment failed')
    expect(workflow).toContain('context="demo-deploy-stage:$stage"')
    expect(workflow).toContain('stage="credentials-failed"')
    expect(workflow).toContain('stage="ssh-stage-failed"')
    expect(workflow).toContain('stage="publish-failed"')
    expect(workflow).toContain('stage="public-verify-failed"')
    expect(workflow).toContain('release_title="$(git log -1 --format=%s "$GITHUB_SHA")"')
    expect(workflow).toContain('release_type="${BASH_REMATCH[1],,}"')
    expect(workflow).toContain('release_title_b64="$(printf \\'%s\\' "$release_title" | base64 -w0)"')
    expect(workflow).toContain('RELEASE_TYPE: ${{ steps.meta.outputs.release_type }}')
    expect(workflow).toContain('RELEASE_TITLE_B64: ${{ steps.meta.outputs.release_title_b64 }}')
    expect(workflow).toContain('EXPECTED_RELEASE_TYPE: ${{ steps.meta.outputs.release_type }}')
    expect(workflow).toContain('EXPECTED_RELEASE_TITLE_B64: ${{ steps.meta.outputs.release_title_b64 }}')
    expect(workflow).toContain("if (current.type !== process.env.EXPECTED_RELEASE_TYPE)")
    expect(workflow).toContain("if (current.title !== expectedTitle)")
  })

  it('checks the staged installer and updates the stable release atomically', () => {
    expect(publisher).toContain('sha256sum "$SOURCE"')
    expect(publisher).toContain('Staged installer checksum mismatch')
    expect(publisher).toContain('IMMUTABLE_PATH="$PUBLIC_BASE_PATH/$VERSION/$INSTALLER"')
    expect(publisher).toContain('LATEST_PATH="$PUBLIC_BASE_PATH/latest/$INSTALLER"')
    expect(publisher).toContain('ln -s "latest/current.json"')
    expect(publisher).toContain('ln -s "latest/VERSION"')
    expect(publisher).toContain('mv -Tf "$NEXT_LINK" "$ROOT/latest"')
    expect(publisher).toContain('RELEASE_TYPE="$8"')
    expect(publisher).toContain('RELEASE_TITLE_B64="$9"')
    expect(publisher).toContain('"channel": "main"')
    expect(publisher).toContain('"type": release_type')
    expect(publisher).toContain('"title": title')
    expect(publisher).toContain('"sha256": sha256')
    expect(publisher).toContain('json.dump({"versions": versions, "releases": releases}')
    expect(publisher).toContain('versions.json')
  })
  it('preserves the legacy version list while adding human release history', () => {
    expect(publisher).toContain('versions.append(name)')
    expect(publisher).toContain('releases.append(release)')
    expect(publisher).toContain('releases.sort(')
    expect(publisher).toContain('"installer": immutable_installer')
    expect(publisher).toContain('"installer": latest_installer')
    expect(publisher).toContain('Release note: [$RELEASE_TYPE] $RELEASE_TITLE')
  })
})
