import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = resolve(__dirname, '../../..')
const workflow = readFileSync(resolve(root, '.github/workflows/windows-package.yml'), 'utf8').replace(/\r\n/g, '\n')
const publisher = readFileSync(resolve(root, 'scripts/publish-demo-release.sh'), 'utf8').replace(/\r\n/g, '\n')

describe('demo server publish contract', () => {
  it('publishes verified semantic main builds to the existing demo release root', () => {
    expect(workflow).toContain("github.ref == 'refs/heads/main'")
    expect(workflow).toContain('needs: package')
    expect(workflow).toContain('actions/download-artifact@v8')
    expect(workflow).toContain('DEV_SSH_HOST')
    expect(workflow).toContain('DEV_SSH_USER')
    expect(workflow).toContain('DEV_SSH_PASSWORD')
    expect(workflow).toContain('SHA256:i5zZS4Ydc4iAFzY8xpI0Md/bi/sCzzwcGMf9P6n06Dc')
    expect(workflow).toContain('Demo SSH host fingerprint mismatch')
    expect(workflow).toContain('/var/www/family-circle-prod/electron-releases/demo')
    expect(workflow).toContain('scripts/publish-demo-release.sh')
    expect(workflow).toContain('https://familycircle.o2gventures.com')
    expect(workflow).toContain('public_base_path="/electron-releases/demo"')
    expect(workflow).toContain('public_path="$public_base_path/latest/$installer"')
    expect(workflow).toContain('RELEASE_VERSION: ${{ needs.package.outputs.release_version }}')
    expect(workflow).toContain('RELEASE_TAG: ${{ needs.package.outputs.release_tag }}')
    expect(workflow).toContain('expected_installer="Family-Circle-Setup-${RELEASE_VERSION}.exe"')
    expect(workflow).toContain('build_id="${RELEASE_VERSION}-main-${GITHUB_SHA:0:7}"')
    expect(workflow).toContain('report-demo-status:')
    expect(workflow).toContain("if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}")
    expect(workflow).toContain('statuses: write')
    expect(workflow).toContain('context="demo-server-deploy"')
    expect(workflow).toContain('stage="credentials-failed"')
    expect(workflow).toContain('stage="ssh-stage-failed"')
    expect(workflow).toContain('stage="publish-failed"')
    expect(workflow).toContain('stage="public-verify-failed"')
    expect(workflow).toContain('stage="release-skipped"')
    expect(workflow).toContain('Server release skipped: commit is not an approved Conventional Commit.')
    expect(workflow).toContain('EXPECTED_TAG: ${{ steps.meta.outputs.release_tag }}')
    expect(workflow).toContain('EXPECTED_BUILD: ${{ steps.meta.outputs.build_id }}')
    expect(workflow).toContain('if (current.tag !== process.env.EXPECTED_TAG)')
    expect(workflow).toContain('if (current.build !== process.env.EXPECTED_BUILD)')
    expect(workflow).toContain('if (current.type !== process.env.EXPECTED_RELEASE_TYPE)')
    expect(workflow).toContain('if (current.title !== expectedTitle)')
  })

  it('reuses an existing immutable release only when retry metadata and checksum match', () => {
    expect(publisher).toContain('Reusing existing verified release destination: $DEST_DIR')
    expect(publisher).toContain('Existing release does not match retry payload')
    expect(publisher).toContain('Existing release installer checksum mismatch')
    expect(publisher).not.toContain('Release destination already exists: $DEST_DIR')
  })

  it('checks the staged installer and updates the stable release atomically', () => {
    expect(publisher).toContain('sha256sum "$SOURCE"')
    expect(publisher).toContain('Staged installer checksum mismatch')
    expect(publisher).toContain('IMMUTABLE_PATH="$PUBLIC_BASE_PATH/$VERSION/$INSTALLER"')
    expect(publisher).toContain('LATEST_PATH="$PUBLIC_BASE_PATH/latest/$INSTALLER"')
    expect(publisher).toContain('ln -s "latest/current.json"')
    expect(publisher).toContain('ln -s "latest/VERSION"')
    expect(publisher).toContain('mv -Tf "$NEXT_LINK" "$ROOT/latest"')
    expect(publisher).toContain('RELEASE_TYPE="$8"')
    expect(publisher).toContain('RELEASE_TITLE_B64="$9"')
    expect(publisher).toContain('RELEASE_TAG="${10}"')
    expect(publisher).toContain('BUILD_ID="${11}"')
    expect(publisher).toContain('"version": version')
    expect(publisher).toContain('"tag": tag')
    expect(publisher).toContain('"build": build')
    expect(publisher).toContain('"channel": "main"')
    expect(publisher).toContain('"type": release_type')
    expect(publisher).toContain('"title": title')
    expect(publisher).toContain('"sha256": sha256')
    expect(publisher).toContain('json.dump({"versions": versions, "releases": releases}')
    expect(publisher).toContain('versions.json')
  })

  it('preserves release history while giving new entries clean semantic identity', () => {
    expect(publisher).toContain('versions.append(name)')
    expect(publisher).toContain('releases.append(release)')
    expect(publisher).toContain('releases.sort(')
    expect(publisher).toContain('"installer": immutable_installer')
    expect(publisher).toContain('"installer": latest_installer')
    expect(publisher).toContain('Published demo release $VERSION ($RELEASE_TAG)')
    expect(publisher).toContain('Build: $BUILD_ID')
    expect(publisher).toContain('Release note: [$RELEASE_TYPE] $RELEASE_TITLE')
  })
})
